INSERT INTO car_makers(name) 
VALUES 
("Acura"),
("Alfa Romeo"),
("AM General"),
("American Motors Corporation"),
("ASC Incorporated"),
("Aston Martin"),
("Audi"),
("Aurora Cars Ltd"),
("Autokraft Limited"),
("Avanti Motor Corporation"),
("Azure Dynamics"),
("Bentley"),
("Bertone"),
("Bill Dovell Motor Car Company"),
("Bitter Gmbh and Co. Kg"),
("BMW"),
("BMW Alpina"),
("Bugatti"),
("Buick"),
("BYD"),
("Cadillac"),
("CCC Engineering"),
("Chevrolet"),
("Chrysler"),
("CODA Automotive"),
("Consulier Industries Inc"),
("CX Automotive"),
("Dabryan Coach Builders Inc"),
("Dacia"),
("Daewoo"),
("Daihatsu"),
("Dodge"),
("E. P. Dutton, Inc."),
("Eagle"),
("Environmental Rsch and Devp Corp"),
("Evans Automobiles"),
("Excalibur Autos"),
("Federal Coach"),
("Ferrari"),
("Fiat"),
("Fisker"),
("Ford"),
("General Motors"),
("Genesis"),
("Geo"),
("GMC"),
("Goldacre"),
("Grumman Allied Industries"),
("Grumman Olson"),
("Honda"),
("Hummer"),
("Hyundai"),
("Import Foreign Auto Sales Inc"),
("Import Trade Services"),
("Infiniti"),
("Isis Imports Ltd"),
("Isuzu"),
("J.K. Motors"),
("Jaguar"),
("JBA Motorcars, Inc."),
("Jeep"),
("Karma"),
("Kenyon Corporation Of America"),
("Kia"),
("Koenigsegg"),
("Laforza Automobile Inc"),
("Lambda Control Systems"),
("Lamborghini"),
("Land Rover"),
("Lexus"),
("Lincoln"),
("London Coach Co Inc"),
("London Taxi"),
("Lotus"),
("Mahindra"),
("Maserati"),
("Maybach"),
("Mazda"),
("Mcevoy Motors"),
("McLaren Automotive"),
("Mercedes-Benz"),
("Mercury"),
("Merkur"),
("MINI"),
("Mitsubishi"),
("Mobility Ventures LLC"),
("Morgan"),
("Nissan"),
("Oldsmobile"),
("Pagani"),
("Panos"),
("Panoz Auto-Development"),
("Panther Car Company Limited"),
("PAS Inc - GMC"),
("PAS, Inc"),
("Peugeot"),
("Pininfarina"),
("Plymouth"),
("Polestar Automotive USA Inc."),
("Pontiac"),
("Porsche"),
("Quantum Technologies"),
("Qvale"),
("Ram"),
("Red Shift Ltd."),
("Renault"),
("Rolls-Royce"),
("Roush Performance"),
("RUF Automobile"),
("Ruf Automobile Gmbh"),
("S and S Coach Company  E.p. Dutton"),
("Saab"),
("Saleen"),
("Saleen Performance"),
("Saturn"),
("Scion"),
("Shelby"),
("smart"),
("Spyker"),
("SRT"),
("Sterling"),
("STI"),
("Subaru"),
("Superior Coaches Div E.p. Dutton"),
("Suzuki"),
("Tecstar, LP"),
("Tesla"),
("Texas Coach Company"),
("Toyota"),
("TVR Engineering Ltd"),
("Vector"),
("Vixen Motor Company"),
("Volga Associated Automobile"),
("Volkswagen"),
("Volvo"),
("VPG"),
("Wallace Environmental"),
("Yugo")
